---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Note on containers:
  # - We use the images provided by geerlingguy, as they provide out-of-the-box
  #   support for Ansible and systemd (needed to test service management).
  # - The containers run as privileged containers so that we can
  #   use systemd functionality. This *should* be possible with unprivileged
  #   containers as well, but is quite the headache.
  - name: nut-netclient-ubuntu-20
    hostname: nut-netclient-ubuntu-20.localdomain
    groups:
      - ubuntu
    image: "geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true

  - name: nut-netclient-ubuntu-18
    hostname: nut-netclient-ubuntu-18.localdomain
    groups:
      - ubuntu
    image: "geerlingguy/docker-ubuntu1804-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true

  - name: nut-netclient-debian-10
    hostname: nut-netclient-debian-10.localdomain
    groups:
      - debian
    image: "geerlingguy/docker-debian10-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true

  - name: nut-netclient-debian-9
    hostname: nut-netclient-debian-9.localdomain
    groups:
      - debian
    image: "geerlingguy/docker-debian9-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: yes
verifier:
  name: ansible
