---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Set up pip
        run: pip3 install --upgrade pip

      - name: Install tox
        run: sudo apt update && sudo apt install -y tox

      - name: Test role
        run: ./test.sh
